exports.getBikeData = () => { 
    return [
        {
            "title": "Bike1",
            "summary": "",
            "frame": "",
            "fork": "",
            "headset": "",
            "bottom_bracket": "",
            "crankset": "",
            "derailleurs": "",
            "shifters": "",
            "handlebars": "",
            "stem": "",
            "seatpost": "",
            "saddle": "",
            "brakes": "",
            "brake_levers": "",
            "pedals": "",
            "tires": "",
            "wheels": "",
            "accessories": "",
            "link" : ""
        },
        {
            "title": "Bike2",
            "summary": "",
            "frame": "",
            "fork": "",
            "headset": "",
            "bottom_bracket": "",
            "crankset": "",
            "derailleurs": "",
            "shifters": "",
            "handlebars": "",
            "stem": "",
            "seatpost": "",
            "saddle": "",
            "brakes": "",
            "brake_levers": "",
            "pedals": "",
            "tires": "",
            "wheels": "",
            "accessories": "",
            "link" : ""
        },
        {
            "title": "Bike3",
            "summary": "",
            "frame": "",
            "fork": "",
            "headset": "",
            "bottom_bracket": "",
            "crankset": "",
            "derailleurs": "",
            "shifters": "",
            "handlebars": "",
            "stem": "",
            "seatpost": "",
            "saddle": "",
            "brakes": "",
            "brake_levers": "",
            "pedals": "",
            "tires": "",
            "wheels": "",
            "accessories": "",
            "link" : ""
        },
        {
            "title": "Bike4",
            "summary": "",
            "frame": "",
            "fork": "",
            "headset": "",
            "bottom_bracket": "",
            "crankset": "",
            "derailleurs": "",
            "shifters": "",
            "handlebars": "",
            "stem": "",
            "seatpost": "",
            "saddle": "",
            "brakes": "",
            "brake_levers": "",
            "pedals": "",
            "tires": "",
            "wheels": "",
            "accessories": "",
            "link" : ""
        },
        {
            "title": "Bike5",
            "summary": "",
            "frame": "",
            "fork": "",
            "headset": "",
            "bottom_bracket": "",
            "crankset": "",
            "derailleurs": "",
            "shifters": "",
            "handlebars": "",
            "stem": "",
            "seatpost": "",
            "saddle": "",
            "brakes": "",
            "brake_levers": "",
            "pedals": "",
            "tires": "",
            "wheels": "",
            "accessories": "",
            "link" : ""
        },
        {
            "title": "Bike6",
            "summary": "",
            "frame": "",
            "fork": "",
            "headset": "",
            "bottom_bracket": "",
            "crankset": "",
            "derailleurs": "",
            "shifters": "",
            "handlebars": "",
            "stem": "",
            "seatpost": "",
            "saddle": "",
            "brakes": "",
            "brake_levers": "",
            "pedals": "",
            "tires": "",
            "wheels": "",
            "accessories": "",
            "link" : ""
        },
        {
            "title": "Bike7",
            "summary": "",
            "frame": "",
            "fork": "",
            "headset": "",
            "bottom_bracket": "",
            "crankset": "",
            "derailleurs": "",
            "shifters": "",
            "handlebars": "",
            "stem": "",
            "seatpost": "",
            "saddle": "",
            "brakes": "",
            "brake_levers": "",
            "pedals": "",
            "tires": "",
            "wheels": "",
            "accessories": "",
            "link" : ""
        }
    ]
}